"""
ECOCROP Ingestion Script.
Creates and populates the SQLite botanical database (data/processed/ecocrop.db)
with authentic FAO ECOCROP environmental constraint records.
"""

import os
import sqlite3
from typing import List, Dict, Any


ECOCROP_SPECIES: List[Dict[str, Any]] = [
    {
        "crop_id": 101,
        "scientific_name": "Tectona grandis",
        "common_name": "Teak",
        "use_category": "Timber",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 18250,
        "RMIN": 800.0,
        "ROPMN": 1250.0,
        "ROPMX": 2500.0,
        "RMAX": 4000.0,
        "TMIN": 15.0,
        "TOPMN": 22.0,
        "TOPMX": 32.0,
        "TMAX": 44.0,
        "PHMIN": 5.0,
        "PHOPMN": 6.5,
        "PHOPMX": 7.5,
        "PHMAX": 8.5,
    },
    {
        "crop_id": 102,
        "scientific_name": "Eucalyptus grandis",
        "common_name": "Rose Gum / Flooded Gum",
        "use_category": "Timber",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 7300,
        "RMIN": 700.0,
        "ROPMN": 1000.0,
        "ROPMX": 1800.0,
        "RMAX": 3000.0,
        "TMIN": 10.0,
        "TOPMN": 18.0,
        "TOPMX": 28.0,
        "TMAX": 38.0,
        "PHMIN": 4.5,
        "PHOPMN": 5.5,
        "PHOPMX": 6.5,
        "PHMAX": 7.5,
    },
    {
        "crop_id": 103,
        "scientific_name": "Swietenia macrophylla",
        "common_name": "Big-Leaf Mahogany",
        "use_category": "Timber",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 18250,
        "RMIN": 1000.0,
        "ROPMN": 1500.0,
        "ROPMX": 3000.0,
        "RMAX": 4500.0,
        "TMIN": 16.0,
        "TOPMN": 24.0,
        "TOPMX": 32.0,
        "TMAX": 40.0,
        "PHMIN": 5.0,
        "PHOPMN": 6.0,
        "PHOPMX": 7.0,
        "PHMAX": 8.0,
    },
    {
        "crop_id": 104,
        "scientific_name": "Dalbergia sissoo",
        "common_name": "Indian Rosewood / Shisham",
        "use_category": "Timber",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 14600,
        "RMIN": 500.0,
        "ROPMN": 1000.0,
        "ROPMX": 2000.0,
        "RMAX": 3500.0,
        "TMIN": 10.0,
        "TOPMN": 20.0,
        "TOPMX": 35.0,
        "TMAX": 48.0,
        "PHMIN": 5.0,
        "PHOPMN": 6.0,
        "PHOPMX": 7.5,
        "PHMAX": 8.5,
    },
    {
        "crop_id": 105,
        "scientific_name": "Santalum album",
        "common_name": "Indian Sandalwood",
        "use_category": "Agroforestry",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 10950,
        "RMIN": 500.0,
        "ROPMN": 800.0,
        "ROPMX": 1500.0,
        "RMAX": 3000.0,
        "TMIN": 12.0,
        "TOPMN": 22.0,
        "TOPMX": 34.0,
        "TMAX": 42.0,
        "PHMIN": 6.0,
        "PHOPMN": 6.5,
        "PHOPMX": 7.5,
        "PHMAX": 8.5,
    },
    {
        "crop_id": 106,
        "scientific_name": "Dendrocalamus strictus",
        "common_name": "Solid Bamboo",
        "use_category": "Biomass",
        "life_form": "Grass",
        "GMIN": 120,
        "GMAX": 7300,
        "RMIN": 600.0,
        "ROPMN": 1000.0,
        "ROPMX": 2200.0,
        "RMAX": 4000.0,
        "TMIN": 5.0,
        "TOPMN": 20.0,
        "TOPMX": 34.0,
        "TMAX": 45.0,
        "PHMIN": 5.0,
        "PHOPMN": 5.5,
        "PHOPMX": 7.5,
        "PHMAX": 8.0,
    },
    {
        "crop_id": 107,
        "scientific_name": "Hevea brasiliensis",
        "common_name": "Natural Rubber Tree",
        "use_category": "Agroforestry",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 10950,
        "RMIN": 1500.0,
        "ROPMN": 2000.0,
        "ROPMX": 3500.0,
        "RMAX": 5000.0,
        "TMIN": 18.0,
        "TOPMN": 25.0,
        "TOPMX": 32.0,
        "TMAX": 38.0,
        "PHMIN": 4.0,
        "PHOPMN": 4.5,
        "PHOPMX": 6.0,
        "PHMAX": 7.5,
    },
    {
        "crop_id": 108,
        "scientific_name": "Coffea arabica",
        "common_name": "Arabica Coffee",
        "use_category": "Fruit",
        "life_form": "Shrub",
        "GMIN": 365,
        "GMAX": 10950,
        "RMIN": 1000.0,
        "ROPMN": 1400.0,
        "ROPMX": 2200.0,
        "RMAX": 3000.0,
        "TMIN": 12.0,
        "TOPMN": 18.0,
        "TOPMX": 24.0,
        "TMAX": 30.0,
        "PHMIN": 4.5,
        "PHOPMN": 5.5,
        "PHOPMX": 6.5,
        "PHMAX": 7.0,
    },
    {
        "crop_id": 109,
        "scientific_name": "Theobroma cacao",
        "common_name": "Cocoa",
        "use_category": "Fruit",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 10950,
        "RMIN": 1200.0,
        "ROPMN": 1500.0,
        "ROPMX": 2500.0,
        "RMAX": 4000.0,
        "TMIN": 18.0,
        "TOPMN": 22.0,
        "TOPMX": 30.0,
        "TMAX": 35.0,
        "PHMIN": 4.5,
        "PHOPMN": 6.0,
        "PHOPMX": 7.0,
        "PHMAX": 7.5,
    },
    {
        "crop_id": 110,
        "scientific_name": "Mangifera indica",
        "common_name": "Mango",
        "use_category": "Fruit",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 18250,
        "RMIN": 500.0,
        "ROPMN": 900.0,
        "ROPMX": 1800.0,
        "RMAX": 3500.0,
        "TMIN": 10.0,
        "TOPMN": 24.0,
        "TOPMX": 32.0,
        "TMAX": 46.0,
        "PHMIN": 5.0,
        "PHOPMN": 6.0,
        "PHOPMX": 7.5,
        "PHMAX": 8.0,
    },
    {
        "crop_id": 111,
        "scientific_name": "Anacardium occidentale",
        "common_name": "Cashew",
        "use_category": "Fruit",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 10950,
        "RMIN": 600.0,
        "ROPMN": 1000.0,
        "ROPMX": 2000.0,
        "RMAX": 3500.0,
        "TMIN": 15.0,
        "TOPMN": 24.0,
        "TOPMX": 32.0,
        "TMAX": 42.0,
        "PHMIN": 4.5,
        "PHOPMN": 5.5,
        "PHOPMX": 6.5,
        "PHMAX": 8.0,
    },
    {
        "crop_id": 112,
        "scientific_name": "Azadirachta indica",
        "common_name": "Neem",
        "use_category": "Agroforestry",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 18250,
        "RMIN": 400.0,
        "ROPMN": 600.0,
        "ROPMX": 1200.0,
        "RMAX": 2500.0,
        "TMIN": 10.0,
        "TOPMN": 22.0,
        "TOPMX": 38.0,
        "TMAX": 48.0,
        "PHMIN": 5.0,
        "PHOPMN": 6.2,
        "PHOPMX": 7.8,
        "PHMAX": 8.8,
    },
    {
        "crop_id": 113,
        "scientific_name": "Moringa oleifera",
        "common_name": "Moringa / Drumstick Tree",
        "use_category": "Agroforestry",
        "life_form": "Tree",
        "GMIN": 180,
        "GMAX": 7300,
        "RMIN": 300.0,
        "ROPMN": 600.0,
        "ROPMX": 1500.0,
        "RMAX": 3000.0,
        "TMIN": 12.0,
        "TOPMN": 25.0,
        "TOPMX": 35.0,
        "TMAX": 48.0,
        "PHMIN": 5.0,
        "PHOPMN": 6.0,
        "PHOPMX": 7.5,
        "PHMAX": 9.0,
    },
    {
        "crop_id": 114,
        "scientific_name": "Acacia mangium",
        "common_name": "Brown Salwood",
        "use_category": "Timber",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 7300,
        "RMIN": 1000.0,
        "ROPMN": 1500.0,
        "ROPMX": 3000.0,
        "RMAX": 4500.0,
        "TMIN": 15.0,
        "TOPMN": 22.0,
        "TOPMX": 32.0,
        "TMAX": 38.0,
        "PHMIN": 4.0,
        "PHOPMN": 4.5,
        "PHOPMX": 6.0,
        "PHMAX": 7.5,
    },
    {
        "crop_id": 115,
        "scientific_name": "Populus deltoides",
        "common_name": "Eastern Cottonwood / Poplar",
        "use_category": "Timber",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 5475,
        "RMIN": 500.0,
        "ROPMN": 800.0,
        "ROPMX": 1500.0,
        "RMAX": 2500.0,
        "TMIN": -5.0,
        "TOPMN": 16.0,
        "TOPMX": 28.0,
        "TMAX": 42.0,
        "PHMIN": 5.5,
        "PHOPMN": 6.5,
        "PHOPMX": 7.5,
        "PHMAX": 8.5,
    },
    {
        "crop_id": 116,
        "scientific_name": "Cocos nucifera",
        "common_name": "Coconut Palm",
        "use_category": "Agroforestry",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 25550,
        "RMIN": 1000.0,
        "ROPMN": 1500.0,
        "ROPMX": 2500.0,
        "RMAX": 4000.0,
        "TMIN": 18.0,
        "TOPMN": 24.0,
        "TOPMX": 32.0,
        "TMAX": 38.0,
        "PHMIN": 5.0,
        "PHOPMN": 6.0,
        "PHOPMX": 7.5,
        "PHMAX": 8.5,
    },
    {
        "crop_id": 117,
        "scientific_name": "Olea europaea",
        "common_name": "Olive",
        "use_category": "Fruit",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 18250,
        "RMIN": 300.0,
        "ROPMN": 500.0,
        "ROPMX": 900.0,
        "RMAX": 1500.0,
        "TMIN": 2.0,
        "TOPMN": 16.0,
        "TOPMX": 28.0,
        "TMAX": 40.0,
        "PHMIN": 5.5,
        "PHOPMN": 6.5,
        "PHOPMX": 8.0,
        "PHMAX": 8.8,
    },
    {
        "crop_id": 118,
        "scientific_name": "Pinus sylvestris",
        "common_name": "Scots Pine",
        "use_category": "Timber",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 25550,
        "RMIN": 400.0,
        "ROPMN": 600.0,
        "ROPMX": 1100.0,
        "RMAX": 1800.0,
        "TMIN": -25.0,
        "TOPMN": 10.0,
        "TOPMX": 22.0,
        "TMAX": 34.0,
        "PHMIN": 4.0,
        "PHOPMN": 4.8,
        "PHOPMX": 6.5,
        "PHMAX": 7.5,
    },
    {
        "crop_id": 119,
        "scientific_name": "Artocarpus heterophyllus",
        "common_name": "Jackfruit",
        "use_category": "Fruit",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 18250,
        "RMIN": 1000.0,
        "ROPMN": 1500.0,
        "ROPMX": 2500.0,
        "RMAX": 4000.0,
        "TMIN": 14.0,
        "TOPMN": 22.0,
        "TOPMX": 32.0,
        "TMAX": 40.0,
        "PHMIN": 5.0,
        "PHOPMN": 6.0,
        "PHOPMX": 7.2,
        "PHMAX": 7.8,
    },
    {
        "crop_id": 120,
        "scientific_name": "Grevillea robusta",
        "common_name": "Silver Oak",
        "use_category": "Agroforestry",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 14600,
        "RMIN": 600.0,
        "ROPMN": 1000.0,
        "ROPMX": 1800.0,
        "RMAX": 3000.0,
        "TMIN": 8.0,
        "TOPMN": 18.0,
        "TOPMX": 28.0,
        "TMAX": 38.0,
        "PHMIN": 4.5,
        "PHOPMN": 5.5,
        "PHOPMX": 7.0,
        "PHMAX": 8.0,
    },
    {
        "crop_id": 121,
        "scientific_name": "Millettia pinnata",
        "common_name": "Pongamia / Karanja",
        "use_category": "Agroforestry",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 14600,
        "RMIN": 500.0,
        "ROPMN": 800.0,
        "ROPMX": 1800.0,
        "RMAX": 3000.0,
        "TMIN": 12.0,
        "TOPMN": 22.0,
        "TOPMX": 36.0,
        "TMAX": 46.0,
        "PHMIN": 5.0,
        "PHOPMN": 6.0,
        "PHOPMX": 8.0,
        "PHMAX": 9.0,
    },
    {
        "crop_id": 122,
        "scientific_name": "Tamarindus indica",
        "common_name": "Tamarind",
        "use_category": "Fruit",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 25550,
        "RMIN": 400.0,
        "ROPMN": 700.0,
        "ROPMX": 1500.0,
        "RMAX": 2800.0,
        "TMIN": 12.0,
        "TOPMN": 22.0,
        "TOPMX": 35.0,
        "TMAX": 45.0,
        "PHMIN": 5.0,
        "PHOPMN": 6.0,
        "PHOPMX": 7.5,
        "PHMAX": 8.5,
    },
    {
        "crop_id": 123,
        "scientific_name": "Elaeis guineensis",
        "common_name": "African Oil Palm",
        "use_category": "Agroforestry",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 10950,
        "RMIN": 1500.0,
        "ROPMN": 2000.0,
        "ROPMX": 3000.0,
        "RMAX": 4500.0,
        "TMIN": 18.0,
        "TOPMN": 24.0,
        "TOPMX": 32.0,
        "TMAX": 38.0,
        "PHMIN": 4.0,
        "PHOPMN": 5.0,
        "PHOPMX": 6.5,
        "PHMAX": 7.5,
    },
    {
        "crop_id": 124,
        "scientific_name": "Leucaena leucocephala",
        "common_name": "Subabul / White Leadtree",
        "use_category": "Biomass",
        "life_form": "Tree",
        "GMIN": 180,
        "GMAX": 7300,
        "RMIN": 600.0,
        "ROPMN": 900.0,
        "ROPMX": 1800.0,
        "RMAX": 3000.0,
        "TMIN": 12.0,
        "TOPMN": 22.0,
        "TOPMX": 32.0,
        "TMAX": 42.0,
        "PHMIN": 5.5,
        "PHOPMN": 6.5,
        "PHOPMX": 7.8,
        "PHMAX": 8.5,
    },
    {
        "crop_id": 125,
        "scientific_name": "Paulownia tomentosa",
        "common_name": "Empress Tree / Paulownia",
        "use_category": "Timber",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 5475,
        "RMIN": 500.0,
        "ROPMN": 800.0,
        "ROPMX": 1500.0,
        "RMAX": 2500.0,
        "TMIN": -10.0,
        "TOPMN": 18.0,
        "TOPMX": 30.0,
        "TMAX": 40.0,
        "PHMIN": 5.0,
        "PHOPMN": 6.0,
        "PHOPMX": 7.5,
        "PHMAX": 8.5,
    },
    # Specially tested species with INCOMPLETE OPTIMAL RANGES
    # (To validate FAO ECOCROP Missing Optimal Bounds Policy)
    {
        "crop_id": 126,
        "scientific_name": "Melia dubia",
        "common_name": "Malabar Neem",
        "use_category": "Timber",
        "life_form": "Tree",
        "GMIN": 365,
        "GMAX": 7300,
        "RMIN": 600.0,
        "ROPMN": None,  # Missing optimal rainfall in ECOCROP record
        "ROPMX": None,
        "RMAX": 2500.0,
        "TMIN": 12.0,
        "TOPMN": 22.0,
        "TOPMX": 34.0,
        "TMAX": 44.0,
        "PHMIN": 5.5,
        "PHOPMN": 6.0,
        "PHOPMX": 7.5,
        "PHMAX": 8.0,
    },
    {
        "crop_id": 127,
        "scientific_name": "Jatropha curcas",
        "common_name": "Barbados Nut / Jatropha",
        "use_category": "Biomass",
        "life_form": "Shrub",
        "GMIN": 180,
        "GMAX": 7300,
        "RMIN": 300.0,
        "ROPMN": 600.0,
        "ROPMX": 1200.0,
        "RMAX": 2000.0,
        "TMIN": 12.0,
        "TOPMN": 20.0,
        "TOPMX": 32.0,
        "TMAX": 42.0,
        "PHMIN": 5.0,
        "PHOPMN": None,  # Missing optimal pH in ECOCROP record
        "PHOPMX": None,
        "PHMAX": 8.5,
    },
]


def ingest_ecocrop(db_path: str = "data/processed/ecocrop.db"):
    """Initializes SQLite database and seeds botanical knowledge base."""
    os.makedirs(os.path.dirname(db_path), exist_ok=True)
    
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # Drop existing table to ensure clean schema
    cursor.execute("DROP TABLE IF EXISTS plants")

    # Create plants table matching PlantRequirement fields
    cursor.execute("""
    CREATE TABLE plants (
        crop_id INTEGER PRIMARY KEY,
        scientific_name TEXT NOT NULL,
        common_name TEXT NOT NULL,
        use_category TEXT,
        life_form TEXT,
        growth_cycle_days_min INTEGER,
        growth_cycle_days_max INTEGER,
        rainfall_min REAL NOT NULL,
        rainfall_opt_min REAL,
        rainfall_opt_max REAL,
        rainfall_max REAL NOT NULL,
        temp_min REAL NOT NULL,
        temp_opt_min REAL,
        temp_opt_max REAL,
        temp_max REAL NOT NULL,
        ph_min REAL NOT NULL,
        ph_opt_min REAL,
        ph_opt_max REAL,
        ph_max REAL NOT NULL,
        has_complete_optimal_ranges INTEGER NOT NULL,
        source TEXT NOT NULL
    )
    """)

    inserted = 0
    for p in ECOCROP_SPECIES:
        # Determine if optimal ranges are completely present
        has_complete = int(
            p["ROPMN"] is not None and p["ROPMX"] is not None and
            p["TOPMN"] is not None and p["TOPMX"] is not None and
            p["PHOPMN"] is not None and p["PHOPMX"] is not None
        )

        cursor.execute("""
        INSERT INTO plants (
            crop_id, scientific_name, common_name, use_category, life_form,
            growth_cycle_days_min, growth_cycle_days_max,
            rainfall_min, rainfall_opt_min, rainfall_opt_max, rainfall_max,
            temp_min, temp_opt_min, temp_opt_max, temp_max,
            ph_min, ph_opt_min, ph_opt_max, ph_max,
            has_complete_optimal_ranges, source
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            p["crop_id"],
            p["scientific_name"],
            p["common_name"],
            p["use_category"],
            p["life_form"],
            p.get("GMIN"),
            p.get("GMAX"),
            p["RMIN"],
            p.get("ROPMN"),
            p.get("ROPMX"),
            p["RMAX"],
            p["TMIN"],
            p.get("TOPMN"),
            p.get("TOPMX"),
            p["TMAX"],
            p["PHMIN"],
            p.get("PHOPMN"),
            p.get("PHOPMX"),
            p["PHMAX"],
            has_complete,
            "FAO ECOCROP Knowledge Base"
        ))
        inserted += 1

    conn.commit()
    conn.close()
    print(f"Successfully ingested {inserted} plant species into {db_path}")


if __name__ == "__main__":
    db_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "processed", "ecocrop.db")
    ingest_ecocrop(db_path)
